name: sql-cmd github action
on:
  push:

jobs:
  publish-sample-api-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the sample-api Docker image
        run: |
          IMAGE_TAG="ghcr.io/jotheesh-joe/sql-cmd:${{ github.sha }}"
          docker build . -f Dockerfile --tag $IMAGE_TAG
          docker push $IMAGE_TAG
